### ISSUE TITLE
psthViewer missing getOr function

### ISSUE THREAD

**Issue by chongtianyifa** [cortex-lab/spikes#17]
Hi Nick,

I was trying your psthViewer function. I found some issues: 1) the function getOr in lines 46-47 is missing. 2) the plotWithErr function is missing. 3) no raster plot comes out. Can you give me a guide on how to fix this?

Thanks,
Chris

**Comment by nsteinme** [comment]
It should be in \visualization\helpers - did you add the full path of the
repository to your matlab path? Or, do you not see that function there?

**Comment by chongtianyifa** [comment]
Thanks for the response. Yes, I found it. I did not add the full path.

**Comment by nsteinme** [comment]
Hm, confusing how that seemed to have been there in 2022 but isn't there now... not sure what this means. Anyway I added it again, sorry about that.

**Comment by GMCadode** [comment]
Great, thanks! Love your visualization program by the way, super helpful at my stage of analysis right now!!
