### ISSUE TITLE
CAR filtering and median trace.

### ISSUE THREAD

**Issue by lauritk** [cortex-lab/spikes#7]
Hi,

in [this](https://github.com/cortex-lab/neuropixels/wiki/Recommended_preprocessing) recommedation there is a line:

"Note that Phase3A probes produce data that is offset from zero (even in the high-pass filtered AP band), so subtracting the median across time of each channel from itself should be done first."

Does it mean that it is better to subtract the median across time of each channel from itself before the CAR, or does it matter? In the function 'applyCARtoDat.m' it is applied afterwards, I think?

**Comment by nsteinme** [comment]
I believe it does matter and I believe the function here subtracts median
across time first...
